spring.application.name=ai-product-finder
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_product_finder
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
openrouter.api.key=${OPENROUTER_API_KEY}
server.port=8080
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
jwt.secret=MyVerySecretKeyForAiProductFinderApplication2026